### ISSUE TITLE
CIS does not process other VS, TS after 1 VS (TS) is not processed successfully.

### ISSUE THREAD

**Issue by dung-tien-nguyen** [F5Networks/k8s-bigip-ctlr#2391]
#### Setup Details
 CIS Version : 2.8.1      
 Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP 16.1.2      
 AS3 Version: 3.30.0      
 Agent Mode: AS3/CCCL       
 Orchestration: K8S/OSCP      
 Orchestration Version:  v1.19.3     
 Pool Mode: Nodeport

#### Description  
 CIS does not process other VS, TS after 1 VS (TS) is not processed successfully. Example when: select unsupported options, domain in tlsProfile does not match domain in VS,...

#### Steps To Reproduce
1) Intentionally initialized 1 VS with incorrect configuration (example VS name: collages.example.com)
2) Initialize 1 VS with correct configuration (example VS name: collages2.example.com)

#### Expected Result 
CIS logs show that IP has been successfully assigned to VS collages2.example.com, status OK. But "kubectl -n <namespace> get tlsprofile,virtualserver -o wide" the IP is not assigned, status not OK. Check at F5 "Local Traffic" > "Virtual Servers" not found VS CIS logs showed.

#### Diagnostic Information
```VS Yaml file for domain: collages.example.com with incorrect clientSSL
<VS Yaml file for domain: collages.example.com with incorrect clientSSL>
---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: college-virtual-servers
  labels:
    f5cr: "true"
  namespace: lb-34-01
spec:
  host: collages.example.com
  tlsProfileName: edge-tls-sft
  ipamLabel: pub-f5
  pools:
    - path: /
      service: service-ext-http
      servicePort: 80
---
apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: edge-tls-sft
  labels:
    f5cr: "true"
  namespace: lb-34-01
spec:
  tls:
    termination: edge             
    clientSSL: /Common/clientssls         ### incorrect config
    reference: bigip 
  hosts:  
  - collage.example.com
```  
```VS Yaml file for domain: collages2.example.com with correct configuration
<VS Yaml file for domain: collages2.example.com with correct configuration>
---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: college-virtual-servers2
  labels:
    f5cr: "true"
  namespace: lb-34-01
spec:
  host: collages2.example.com
  ipamLabel: pub-f5
  pools:
    - path: /
      service: service-ext-http
      servicePort: 80
```  
#### Observations (if any)
Logs when deploys VS collages.example.com (VS incorrect configuration)
![image](https://user-images.githubusercontent.com/35716865/166651849-30c15388-a8d7-40a0-9971-046c13f08c07.png)
Logs when deploys VS collages2.example.com (VS correct configuration) after deploy collages.example.com
![image](https://user-images.githubusercontent.com/35716865/166652109-e7f565e9-0fe0-41fe-8326-fc7df2098365.png)
kubectl -n <namespace> get tlsprofile,virtualserver -o wide
![image](https://user-images.githubusercontent.com/35716865/166652916-c02386e5-870c-4fc2-8a8d-becbae4959e9.png)
Check on F5
![image](https://user-images.githubusercontent.com/35716865/166653044-3fe569a8-2dcd-4ade-abd3-0db9b711a976.png)

**Comment by hainamtvvt** [comment]
The same issue, please  send help !!

**Comment by HuTiuOnTheCloud** [comment]
...

**Comment by trinaths** [comment]
Created [CONTCNTR-3375] for internal tracking.

**Comment by kylinsoong** [comment]
I have hit this issue as well.

**Comment by lavanya-f5** [comment]
Invalid configuration at client side is validated by CIS like incorrect tlsProfileName and processing is skipped for invalid config and CIS continues posting other config.

But if invalid config is w.r.to config referenced on bigip, CIS cant validate so AS3 is posted  and 422 returned from bigip.

**Comment by mikejoh** [comment]
We're hitting this at times also, any updates on this? We're running CIS `v2.10.1` at the moment. Thanks.

**Comment by trinaths** [comment]
@mikejoh Please share CIS debug for this issue.

**Comment by mikejoh** [comment]
> @mikejoh Please share CIS debug for this issue.

Unfortunately i don't, not more than already has been shared in this issue and https://github.com/F5Networks/k8s-bigip-ctlr/issues/2383. It's basically exactly what we're seeing. 

For us the biggest problem right now is that we're running the F5 BIGIP with `--pool-member-type=cluster` and populating the pools with `Endpoint`'s from the cluster. This means that if we have a set of `VirtualServer` (20+ in our case) and one of them is having a configuration issue of some sort resulting in a `422` from AS3, it blocks updates of new Pod IPs to the pools. So at times we can have pools with stale info in them which results in service outage, the deployment in the cluster rolled out just fine but the `VirtualServer` had a configuration error (like referencing something not available/existing in the F5 LB).

**Comment by trinaths** [comment]
Made changes to remove invalid tenant from retry map. So when correct config is updated, CIS posts the declaration else it logs the 422 ERROR and doesn't retry

PR: https://github.com/F5Networks/k8s-bigip-ctlr/pull/2544

Closing as issue is fixed.

**Comment by mikejoh** [comment]
@trinaths I think you closed this down a bit too fast.. This is still an issue for us on `v2.10.1` and `v2.11.1`. Let me take you through the logs:

Notes:
* `k8s-bigip-ctlr` is running with `--pool-member-type=cluster`. We're load balancing directly to Pod IPs, not through NodePorts basically.
* Tested on `v2.10.1` and `v2.11.1`.
* F5 LB on the other end is running `15.1.7` of TMOS.
* We have the following `f5-appsvcs` package installed: `f5-appsvcs-3.38.0-4.noarch`

1. I'm updating an existing `TLSProfile` referenced in an existing `VirtualServer` with the following:
* `reference: bigip` (was `secret`)
* `clientTLS: /Common/does-not-exist`
```
2023/02/06 20:42:52 [DEBUG] Processing Key: &{nginx TLSProfile nginx-tlsprofile 0xc0000ce1a0 Update}
2023/02/06 20:42:52 [INFO] Enqueueing TLSProfile
```
2. This fails as expected resulting in a `422` response:
```
2023/02/06 20:42:52 [DEBUG] [AS3] PostManager Accepted the configuration
2023/02/06 20:42:52 [DEBUG] [AS3] posting request to https://f5-lb.example.com/mgmt/shared/appsvcs/declare/cluster-partition
2023/02/06 20:43:02 [ERROR] [AS3] Raw response from Big-IP: map[code:422 declarationFullId: message:Unable to find /Common/does-not-exist for /cluster-partition/Shared/nginx_443/serverTLS/0]
```
3. No problems so far, now i deleted a Pod in a Pool referenced in another `VirtualServer` (that works just fine at this moment), mimics a e.g. Deployment where all Pods are terminated and recreated. Since they'll get new Pod IPs, these needs to be updated in the F5 pools. The F5 controller picks something up here:
```
2023/02/06 20:45:07 [DEBUG] Enqueueing Endpoints: &Endpoints{ObjectMeta:{working-nginx  kube-system  65f78d08-ebb5-4440-a3e2-b70235f469a2 34329803 0 2022-12-13 08:42:47 +0000 UTC <nil> <nil> map[app.kubernetes.io/managed-by:Helm k8s-app:hubble-ui] map[] [] []  [{kube-controller-manager Update v1 2023-01-16 15:11:37 +0000 UTC FieldsV1 {"f:metadata":{"f:labels":{".":{},"f:app.kubernetes.io/managed-by":{},"f:k8s-app":{}}}}}]},Subsets:[]EndpointSubset{},}
2023/02/06 20:45:07 [DEBUG] Processing Key: &{kube-system Endpoints working-nginx 0xc00054a3c0 Update}
2023/02/06 20:45:09 [DEBUG] Enqueueing Endpoints
```
4. The service is now down in the F5 and the pool reports the backend as down, and i can see that it's the old IP address the Pod had before i deleted it. If i correct the error in the `TLSProfile` soon after the F5 now has correct info in the Pool of that other `VirtualServer`.

So i would state,  AFAICT, that the issue is not fixed with PR #2544 and it's still there. Or at least something is totally off, do you want me to create another issue?

**Comment by trinaths** [comment]
@mikejoh Please raise a new issue with more info.
